general:
  world_frame: "odom"
  publish_performance_stats: false

map:
  pruning_period: { seconds: 10.0 }
  visualization_period: { seconds: 10.0 }
  autosave_period: { seconds: -1.0 }
  autosave_path: ""
  data_structure:
    type: "wavelet_octree"
    min_cell_width: &min_cell_width { meters: 0.2 }
    max_height: 14

integrators:
  - input:
      type: "pointcloud"
      topic_name: "/os1_cloud_node/points"
      topic_queue_length: 10
      max_wait_for_pose: { seconds: 1.0 }
    integration_method:
      type: "coarse_to_fine_wavelet_integrator"
      min_range: { meters: 1.0 }
      max_range: { meters: 20.0 }
      max_acceptable_update_error: 0.1
      max_update_resolution: *min_cell_width
    projection_model:
      type: "ouster_projector"
      lidar_origin_to_beam_origin: { millimeters: 27.67 }
      lidar_origin_to_sensor_origin_z_offset: { millimeters: 36.18 }
      elevation:
        num_cells: 64
        min_angle: { degrees: -15.594 }
        max_angle: { degrees: 17.743 }
      azimuth:
        num_cells: 1024
        min_angle: { degrees: -180.0 }
        max_angle: { degrees: 180.0 }
    measurement_model:
      type: "continuous_volumetric_log_odds"
      angle_sigma: { degrees: 0.05 }
      range_sigma: { meters: 0.05 }
      scaling_free: 0.2
      scaling_occupied: 0.4
