common:
  msg_source: 2
  send_packet_ros: false
  send_point_cloud_ros: true
lidar:
  - driver:
      lidar_type: RSBP
      start_angle: 0
      end_angle: 360
      min_distance: 0.2
      max_distance: 200
      use_lidar_clock: false
    ros:
      ros_recv_packet_topic: /bpearl_front/packets
      ros_send_point_cloud_topic: /bpearl_front/points
  - driver:
      lidar_type: RSBP
      start_angle: 0
      end_angle: 360
      min_distance: 0.2
      max_distance: 200
      use_lidar_clock: false
    ros:
      ros_recv_packet_topic: /bpearl_rear/packets
      ros_send_point_cloud_topic: /bpearl_rear/points
